version: '3.7'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=apikey
    volumes:
      - "C:/Users/svaad/Documents/csv-files:/app/csv"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-data:

  